### ISSUE TITLE
Plugin installation override the doctrine migration_paths order

### ISSUE THREAD

**Issue by MacBim** [BitBagCommerce/SyliusWishlistPlugin#51]
Sylius version : 1.9
Plugin version : v1.5.3

After installing the plugin, I noticed that all the migrations that we create using the doctrine:migrations:diff (or :generate) ends up in the plugins migration folder, instead of the project's directory.

Turns out the plugin's BitBagSyliusWishlistExtension class prepend its migration_path, causing the following thing :
<img width="921" alt="image" src="https://user-images.githubusercontent.com/11718596/115387250-b2d24800-a1da-11eb-8d42-e0b815e03078.png">

Migrations are correctly setup in our project (see our config/packages/doctrine_migrations.yaml file)
<img width="604" alt="image" src="https://user-images.githubusercontent.com/11718596/115387321-ced5e980-a1da-11eb-8e7d-1699fa83bc42.png">

Is there a reason as to why this approach was chosen instead of a doctrine:migrations:diff then :migrate ?

Thanks

**Comment by piotrkardasz** [comment]
Hello @MacBim we are planning to remove migrations from a bundle because it can cause order priority issues and then the correct approach will be `bin/console doctrine:migrations:diff` depends on the App context. 

I confirm it is a bug
At this moment You can workaround by using `doctrine:migrations:diff --namespace=App\\Migrations` command to generate migration in right place.

**Comment by piotrkardasz** [comment]
@MacBim now you can update the package to version `v1.5.4` and `migration_path` will be ordered correctly.

**Comment by MacBim** [comment]
Amazing, thank you, will update shortly
